include: package:flutter_lints/flutter.yaml

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options

analyzer:
  exclude:
    - web_demo/**
    - example/**

linter:
  rules:
    always_use_package_imports: true
    avoid_empty_else: true
    always_specify_types: false
    prefer_single_quotes: true
    sort_child_properties_last: true
    avoid_unnecessary_containers: true
    use_build_context_synchronously: true
    require_trailing_commas: true
    unnecessary_lambdas: true
    avoid_print: true
    omit_local_variable_types: true
    avoid_types_on_closure_parameters: true
    prefer_final_fields: true
    prefer_final_locals: true