name: kalender
description: A highly customizable calendar widget with day, multi-day, month and schedule views, drag-and-drop rescheduling, event resizing, and timezone support.
version: 0.27.0-dev.2
repository: https://github.com/werner-scholtz/kalender.git
issue_tracker: https://github.com/werner-scholtz/kalender/issues
topics:
  - calendar
  - widget
  - scheduler
  - timezone
  - drag-and-drop

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  collection: ^1.19.1
  flutter:
    sdk: flutter
  intl: '>=0.19.0 <0.23.0'
  linked_pageview: ^1.1.0
  meta: ^1.9.0
  scrollable_positioned_list: ^0.3.8
  timezone: '>=0.11.0 <0.12.0'
  universal_platform: ^1.1.0

dev_dependencies:
  benchmark_harness: ^2.3.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
